C2DEVEL-10278: add boto spec and makefile
C2Devel/boto3 pull request #1
Opened 2021-02-24 12:32 UTC by ancient07

2021-02-24 13:13 UTC, Sharpeye90 requested changes
requires = [
    'botocore>=1.18.15,<1.19.0',
    'jmespath>=0.7.1,<1.0.0',
    's3transfer>=0.3.0,<0.4.0'
]

Надо еще добавить вот такую зависимость в Requires, чтоб вместе с бото приезжали те зависимости, которые требуются для ее работы.

2021-02-24 13:35 UTC, ancient07 commented
> requires = [
> 'botocore>=1.18.15,<1.19.0',
> 'jmespath>=0.7.1,<1.0.0',
> 's3transfer>=0.3.0,<0.4.0'
> ]
> 
> Надо еще добавить вот такую зависимость в Requires, чтоб вместе с бото приезжали те зависимости, которые требуются для ее работы.

в спеку?

2021-03-03 17:16 UTC, Sharpeye90 requested changes

2021-03-03 17:16 UTC, Sharpeye90 commented on python-boto3.spec
> +Version:        1.17.14
Почему именно эта версия? Я полагаю эта была самой свежей. Лучше заскоупиться на конкретной версии. Надо спросить у ответственных разрабов какая им подойдет. Из разрабов бото3 хотели Дима Плякин и Руслан. Я бы еще форсил именно 1.15.15 - так как она была в epel8.

2021-03-04 14:10 UTC, ancient07 commented on python-boto3.spec
> +Version:        1.17.14
Зафиксировал послденюю версию бото3 на момент подготовки

2021-03-15 11:17 UTC, Sharpeye90 approved these changes

2021-03-15 14:20 UTC, merged